name: Build and publish a Docker image to ghcr.io
on:
  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - criteo-pre-release
      - criteo-release
      - criteo-main

jobs:
  docker_publish:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        env:
          OPERATOR_IMG: ghcr.io/criteo-forks/verticadb-operator:${{ env.GITHUB_REF_NAME }}-${{ env.GITHUB_SHA }}
          TARGET_ARCH: linux/amd64
        run: |
          make docker-build-operator
          make docker-push-operator;
